export interface IMuiscUser {
  uin: number
  nick: string
  mark: string
  headurl: string
  identify: number
  singerid: number
  desc: string
  ifpicurl: string
  extra: string
  vec_type: unknown[]
  vec_rel_singer_id: unknown[]
  pendantInfo: {
    staticImg: string
    dynamicImg: string
    status: number
    id: number
  }
  gender: number
  logos: null
  birthday: {
    date: number
    from: number
    update: number
    count: number
    intervalSec: number
    hint: string
    canAlter: number
  }
  AdSigned: number
  C4BAutoPay: number
  CPLoverAutoPay: number
  CPLoverEnd: string
  CPLoverFlag: number
  CPLoverStart: string
  DtsEffectsTyan: number
  ExpVip: number
  FfbLevel: number
  FfbNextScore: number
  FfbNextlevel: number
  FfbScore: number
  FfbYearEndTime: string
  FfbYearStartTime: string
  Ffbdayscore: number
  Ffbneedday: number
  Ffbpayway: number
  Ffbpercent: number
  Ffbyear: number
  GlxySndTyan: number
  HYYYEndTime: string
  HYYYFlag: number
  HYYYStartTime: string
  HugeAutoPay: number
  HugeLoverAuto: number
  HugeUpgrade: number
  HugeVip: number
  HugeVipEnd: string
  HugeVipStart: string
  HugeYearEnd: string
  HugeYearFlag: number
  HugeYearStart: string
  LMAutoPay: number
  LMEnd: string
  LMFlag: number
  LMStart: string
  LMTiyan: number
  LvHaoAutoPay: number
  LvScore: number
  MainAdsFreeEndTs: number
  MidasLoverEnd: number
  MidasLoverFlag: number
  MidasLoverStart: number
  MstSndTyan: number
  OverseaEndTime: string
  OverseaFlag: number
  OverseaStartTime: string
  UnionFreeEndTs: number
  WxOpenId: string
  XiaoMiAutoPay: number
  XingZuanEndTime: string
  XingZuanStartTime: string
  YellowEndTime: string
  YellowStartTime: string
  cachePolicyFlag: number
  canRenew: number
  eightEndTime: string
  eightStartTime: string
  ffbAutoPay: number
  hardwareFlag: number
  hq_try_off_date: number
  hsq_try_off_date: number
  iBuyFromMobile: number
  iCurLevel: number
  iDayValue: number
  iFirstOpen: number
  iGreyBuylvzuan: number
  iHisDiff: number
  iHisEnd: number
  iHisPeriodDown: number
  iHisStart: number
  iLimitNum: number
  iListenDays: number
  iMusicLevel: number
  iNeedCheckEightTwelveTime: number
  iNewSuperVip: number
  iNewVip: number
  iNextLevel: number
  iNextValue: number
  iNoLimitFlag: number
  iNowEnd: number
  iNowStart: number
  iPayWay: number
  iPneedBuy: number
  iPostPay: number
  iSuperVip: number
  iUpGradeDay: number
  iUpGradePec: number
  iVipFlag: number
  iWeilaiCarVip: number
  iXingZuanLevel: number
  iXingZuanScore: number
  iXingZuanVip: number
  iYearFlag: number
  iYearXingZuanVip: number
  iYearYellowVip: number
  iYellowLevel: number
  iYellowScore: number
  iYellowVip: number
  ieight: number
  itwelve: number
  nDownAlrdy: number
  nRemain: number
  newFreeUserAlertTimes: number
  newFreeUserFlag: number
  newFreeUserGetTimes: number
  sIcon: string
  sOverDate: string
  sOverDateTime: string
  sPayWayDetail: string
  sStartDateTime: string
  sVendor: string
  sWeilaiCarEnd: string
  sWeilaiCarStart: string
  sq_try_off_date: number
  strDownPeriodEnd: string
  strDownPeriodStart: string
  strHIsDownPeriodStart: string
  strHisDownPeriodEnd: string
  strStartBuyTime: string
  strYearEndTime: string
  strYearStartTime: string
  strYearXingZuanEndTime: string
  strYearXingZuanStartTime: string
  strYearYellowEndTime: string
  strYearYellowStartTime: string
  superAutoPay: number
  superEndTime: string
  superStartTime: string
  twelveEndTime: string
  twelveStartTime: string
  uUin: number
}
